name: CI Testing

on:
  push:
    branches:
      - master
      - users/carson/migrate_to_gha # TODO remove after done dev
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      custom_zosmf_host:
        description: ZOSMF host
        type: string
        required: false
      custom_zosmf_port:
        description: ZOSMF port
        type: string
        required: false
      custom_ssh_port:
        description: SSH port
        type: string
        required: false
      custom_directory_root:
        description: Testing root directory
        type: string
        required: false

env:
  # TODO need a way to switch the marist credentials - use a GHA environment to hold host/ports and credentials?
  INTEGRATION_TEST_DIRECTORY_ROOT: ${{ github.event.inputs.custom_directory_root || '/ZOWE/tmp'  }}
  SSH_PORT: ${{ github.event.inputs.custom_ssh_port || 22 }}
  ZOSMF_HOST: ${{ github.event.inputs.custom_zosmf_host || 'zzow04.zowe.marist.cloud' }}
  ZOSMF_PORT: ${{ github.event.inputs.custom_zosmf_port || 10443 }}
  UID: jobs-integration-test-${{ github.run_id }}

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    services: # TODO use conformant containers
      discovery-service:
        image: ghcr.io/balhar-jakub/discovery-service:latest
        volumes: # TODO need to mount with zosmf on marist registration
          - /api-defs:/api-defs
      gateway-service:
        image: ghcr.io/balhar-jakub/gateway-service:latest
      mock-services:
        image: ghcr.io/balhar-jakub/mock-services:latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup

      - name: Build with Gradle
        run: ./gradlew build

      - name: Unit test with Gradle
        run: ./gradlew coverage

      - name: Test apiml is up
        run: |
          echo $(curl https://gateway-service:7554/gateay/api/v1/)

      # TODO need a lock for integration testing? lock("jobs-integration-test-at-${params.INTEGRATION_TEST_ZOSMF_HOST}-${params.INTEGRATION_TEST_ZOSMF_PORT}") - could concurrency limitation help here?
      # TODO run apiml in GHA not on marist? Maybe use containers in GHA to create a network? or apiml runs on marist and -Pserver.host use marist host
#      - name: Setup APIML for integration tests
#        run: |
#          chmod +x scripts/prepare-fvt.sh
#          ./scripts/prepare-fvt.sh
#          sleep 2m # Let setup finish
#        env:
#          FVT_ZOSMF_HOST: ${{ env.ZOSMF_HOST }}
#          FVT_ZOSMF_PORT: ${{ env.ZOSMF_PORT }}
#          FVT_SERVER_SSH_HOST: ${{ env.ZOSMF_HOST }}
#          FVT_SERVER_SSH_PORT: ${{ env.SSH_PORT }}
#          FVT_SERVER_SSH_USERNAME: ${{ secrets.MARIST_USERNAME }}
#          FVT_SERVER_SSH_PASSWORD: ${{ secrets.MARIST_PASSWORD }}
#          FVT_SERVER_DIRECTORY_ROOT: ${{ env.INTEGRATION_TEST_DIRECTORY_ROOT }}
#          FVT_UID: ${{ env.UID }}

# TODO I think can remove server.test.directory? And therefore cleanup? Definitely can stop the cleanup if apiml is local
      - name: Intregration tests for v1 - LTPA
        run: >
          ./gradlew runIntegrationTests
          -Pserver.host=gateway-service
          -Pserver.port=7554
          -Pserver.username=${{ secrets.MARIST_USERNAME }}
          -Pserver.password=${ secrets.MARIST_PASSWORD }}
          -Pserver.test.directory=${{ env.INTEGRATION_TEST_DIRECTORY_ROOT }}/${ env.UID }}
          -Ptest.version=1

      - name: Intregration tests for v2 - JWT
        run: >
          ./gradlew runIntegrationTests
          -Pserver.host=gateway-service
          -Pserver.port=7554
          -Pserver.username=${{ secrets.MARIST_USERNAME }}
          -Pserver.password=${ secrets.MARIST_PASSWORD }}
          -Pserver.test.directory=${{ env.INTEGRATION_TEST_DIRECTORY_ROOT }}/${ env.UID }}
          -Ptest.version=2

      - name: Store test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: TestResults
          path: |
            build/reports/jacoco/jacocoFullReport/html
            jobs-api-server/build/reports/tests/test
            jobs-tests/build/reports/tests/test-1
            jobs-tests/build/reports/tests/test-2

      - name: Display integration test logs
        if: always()
        run: |
          find .fvt/logs -type f | xargs -i sh -c 'echo \">>>>>>>>>>>>>>>>>>>>>>>> {} >>>>>>>>>>>>>>>>>>>>>>>\" && cat {}'

      - name: Clean up integration test directory
        if: always()
        run: |
          SSHPASS=${{ secrets.MARIST_PASSWORD }} sshpass -e ssh -tt -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -p ${{ env.SSH_PORT }} ${{ secrets.MARIST_USERNAME }}@${{ env.ZOSMF_HOST }} << EOF
          cd ~
          [ -d "${{ env.INTEGRATION_TEST_DIRECTORY_ROOT }}/${{ env.UID }}" ] && rm -fr ${{ env.INTEGRATION_TEST_DIRECTORY_ROOT }}/${{ env.UID }}

      - uses: ./.github/actions/teardown
        if: always()

  sonarQubeScan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup
        with:
          jdkVersion: 11

      - name: Sonar scan with Gradle
        run: >
          ./gradlew coverage sonarqube
          -Psonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
          -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_PASSWORD
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - uses: ./.github/actions/teardown
