name: Image publish branch

on:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      imageVersion: ${{ steps.outputVersion.outputs.version }}
    steps:
      - name: Output version using branch
        id: outputVersion
        run: |
          # Replace / and _ with - in branch name
          cleanBranchName=$(echo "$BRANCH_NAME" | sed -e "s/\//-/g" | sed "s/_/-/g")
          gradlePropertiesVersion=$(cat ./gradlew.properties | grep version= | awk -Fversion= '{print$2}')
          echo "::set-output name=version::$gradlePropertiesVersion$cleanBranchName"

  publish-images:
    needs: get-version
    uses: zowe/explorer-jobs/.github/workflows/build-images.yml@master
    with:
      forceNoRelease: true
      versionOverride: ${{ needs.get-version.outputs.imageVersion }}
    secrets:
      registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
      registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
      redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
      redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
      zlinux-host: ${{ secrets.ZLINUX_HOST }}
      zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
      zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
      zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}