name: Image specific release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version that is going to be release'
        required: true

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # TODO need to build and unit test

  PublishImages:
    needs: BuildAndTest
    uses: zowe/explorer-jobs/.github/workflows/build-images.yml@users/carson/migrate_to_gha # TODO change to master
    with:
      version: ${{ github.event.inputs.release_version }}
    secrets:
      registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
      registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
      redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
      redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
      zlinux-host: ${{ secrets.ZLINUX_HOST }}
      zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
      zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
      zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}